### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Matteoo98** [chris-greening/instascrape#78]
Hi, i'm receiving always the error : "InstagramLoginRedirectError", so i want to login. 
Taking as example your code : 
# Instantiate the scraper objects 
`google = Profile('https://www.instagram.com/google/')`
# Scrape their respective data 
`google.scrape()`

How can i login with username and password ?

**Comment by tarob0ba** [comment]
Based on what I've seen in the source, I believe (~95%) that you should pass your Instagram session id to the ```scrape``` method as indicated by the exception, but you should confirm with @chris-greening, since I don't have an account to test this. 

```python
from instascrape import *

session_id = '' # Your session ID - http://valvepress.com/how-to-get-instagram-session-cookie/

google = Profile('https://www.instagram.com/google/')

headers = {"user-agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Mobile Safari/537.36 Edg/87.0.664.57",
           "cookie": f"sessionid={session_id};"}

google.scrape(headers=headers)

print(google.followers)
```

**Comment by chris-greening** [comment]
@beckettnormington nailed it exactly, thank you so much! 

@Matteoo98, Instagram has been making it increasingly harder to scrape data from their platform so for the most part, you will have to pass a valid session ID as a cookie (as shown above in Beckett's sample code). 

Unfortunately, instascrape itself doesn't provide login capabilities as of right now because it runs the risk of getting an account flagged as suspicious but you can manually find your session ID by [following these steps](http://valvepress.com/how-to-get-instagram-session-cookie/). 

Hope this helps!

**Comment by Matteoo98** [comment]
Yes this would avoid problems, but how long does the session last ? I think that would be more efficent if i will implement a login first then get the sessionid and each time control the validity and in case repeat the login. What is your take on this ?

**Comment by drctoday** [comment]
> @beckettnormington nailed it exactly, thank you so much!
> 
> @Matteoo98, Instagram has been making it increasingly harder to scrape data from their platform so for the most part, you will have to pass a valid session ID as a cookie (as shown above in Beckett's sample code).
> 
> Unfortunately, instascrape itself doesn't provide login capabilities as of right now because it runs the risk of getting an account flagged as suspicious but you can manually find your session ID by [following these steps](http://valvepress.com/how-to-get-instagram-session-cookie/).
> 
> Hope this helps!

Hi Chris,

I am pretty sure I am passing the Session Id (from Google Chrome -- Inspect -- Application -- Instagram -- Session Id, and my Instagram account is logged in). However, I still receive a message indicates that I need to pass an active session id as cookie. 

"InstagramLoginRedirectError: Instagram is redirecting you to the login page instead of the page you are trying to scrape. This could be occuring because you made too many requests too quickly or are not logged into Instagram on your machine. Try passing a valid session ID to the scrape method as a cookie to bypass the login requirement"

**Comment by logbasex** [comment]
> 

I'm facing the same problem.

**Comment by haresh14** [comment]
I am facing the same problem
